### ISSUE TITLE
INiTS Logo as Supporter on Website

### ISSUE THREAD

**Issue by Kriszlina** [GDGVienna/wtmvienna-site#10]
![inits logo rgb](https://cloud.githubusercontent.com/assets/16474970/12032804/95562e0c-ae1c-11e5-94cf-e4c89568a5eb.png)

**Comment by helmuthb** [comment]
Krisz, there was already a logo (please always refer to the test site for the latest version: http://test.womentechmakers.at/)

**Comment by Kriszlina** [comment]
Ah ok, I see. But when do the changes go online then?

Thanks!
