### ISSUE TITLE
Update Team Page

### ISSUE THREAD

**Issue by Kriszlina** [GDGVienna/wtmvienna-site#12]
Need photos from new Team members: Philipp, Pilar and Kariem and links to profiles they want to share.

**Comment by kariem** [comment]
I've just added pull request #13 for my changes - was not sure if there are problems when I commit directly to master, as it's published immediately. I usually prefer someone else to merge the pull request.

However we will need the updates from the others too. Please add here as comment or update the pull request, or add your own. Then check off the list below.

_Note_: From what I've seen on the [team list](http://womentechmakers.at/team/), the following _profiles_ are ok: Facebook, Twitter, Google Plus, Github, Website. Also look at [_sprites.scss](https://github.com/GDGVienna/wtmvienna-site/blob/8055d7fcbba0f59ff94e03b7959d2032dae2214a/_sass/partials/_sprites.scss) - everything starting with `icon-`.

Check off this list as soon as your images and profile links are either in a comment here or in a pull request:

- [ ] Pilar 
- [ ] Philipp
- [x] Kariem

If there are no objections, I would like to extend this issue to update the team site based on the current organization (see [Krisz' mail from September](https://groups.google.com/d/msg/wtm-core-team/sBzXUKrlQ7s/n6qe7lXwBQAJ)).

/cc @Althaire, @Kriszlina  (don't have Philipp's)
