### ISSUE TITLE
Add Helga to team page

### ISSUE THREAD

**Issue by Kriszlina** [GDGVienna/wtmvienna-site#17]
Profile to LinkedIn is: https://at.linkedin.com/in/hturcanu
![_mg_9504 1](https://cloud.githubusercontent.com/assets/16474970/12612170/23781f34-c4f1-11e5-9b3a-b7b24be355bc.jpg)

**Comment by helmuthb** [comment]
Implemented on testbed:
http://test.womentechmakers.at/team
