### ISSUE TITLE
Compass as Gold Sponsor on Website

### ISSUE THREAD

**Issue by Kriszlina** [GDGVienna/wtmvienna-site#18]
Please add their logo on the website so I can share it online :)
![logo_compass_gruppe_farbe](https://cloud.githubusercontent.com/assets/16474970/12920373/a8d8a9f8-cf48-11e5-8e97-11f58d4e3ff4.jpg)

**Comment by helmuthb** [comment]
Added to the website as gold sponsor.

Shall I move INiTS up to Gold as well?

**Comment by helmuthb** [comment]
Added INiTS to the Gold sponsors group as well.

**Comment by Kriszlina** [comment]
Thank you! :)
