### ISSUE TITLE
Stefanie as speaker, after Birgit and Before Nino

### ISSUE THREAD

**Issue by Kriszlina** [GDGVienna/wtmvienna-site#21]
So Nino is the last speaker, before her Stefanie should go. 

Info:

TITLE:  Effective communication in IT projects as a success factor - why women are the perfect match

ABSTRACT: developers, architects or other IT specialists with extended technical knowledge who evolved to become project managers.
There are various possible explanations for this. One is that project management is that having profound knowledge in IT domain is usually considered as essential prerequisite to become an IT project manager.
Looking at the gender distribution in IT it is very clear that women are currently underrepresented. According to statistics only around 15% of all IT students are female, which is impacting also the number of employed women in IT.
I am a passionate project manager for IT and technical projects. Although I have completed a technical study programme I was never a so called “IT pro”. In the beginning of my career I encountered many situations where I was doubting if I had the right skills or if the absence of detailed IT knowledge was a real problem in my job. Despite my doubts I took on every possible project and grew with the challenges. Looking back, I have successfully managed a lot of different projects in the last years. So I was starting to ask myself what was the main factor to succeed in IT project management without being an IT pro? I came to the conclusion that it's all about effective communication, which is in my opinion an underestimated key success factor in IT projects.
What my work experience has taught me is that it is possible to manage IT projects without having detailed technical know-how but being a good communicator and enabler for a great team of specialists you can rely on instead.
Looking closer at the competence profile the international project management association has published in its competence baseline supports my insight. A project manager needs to have a big set of different skills. On the one side there are the "hard" skills like financial management, risk and quality management, managing the project's goals, stakeholders, resources and many more. On the other side there is also an immense focus on the so called "soft" skills - communication, team work, problem-solving, conflict and crisis management, openness and even creativity.
Effective communication is needed in every second of the project from start to the end -  building and forming the team, leading the team on the path to success, managing project crises, dealing with customers when negotiating change requests, sorting human disputes, keeping the team's spirit in hard times until the successful closing of the project.
In contradiction to the classical view of project management in IT, there exists also another approach: IT project managers who are exactly the contrary - great communicators with technical understanding as well as a passion for the field of IT.
Numerous studies exist about why women would be better leaders than men. The aim of this talk is not to fuel up the discussion about who is a better leader – women or men. The aim is to outline why women are the perfect match based on this changed perspectives in IT project management and should consider this seriously as career path even tough without being an IT pro. 

ABOUT YOU: I am a 31-year-old team lead for project management currently employed at Becton Dickinson Austria and responsible for implementing medical software projects.
Although I have completed a technical study programme with the focus on sports equipment technology I was never a so called “IT pro”. Nevertheless, I was always attracted by managing IT and technical projects with a certain passion for health tech. The main steps of my career include being part of and establishing a startup in the field of e-Health and ambient assisted living, working as an IT project manager at a Scandinavian IT company and my current job as team lead. I have been managing a lot of projects ranging from research and development projects in IT, implementing a quality management system for medical software, leading SAP implementation projects without having ever opened a SAP system myself to managing and winning multimillion tenders for IT projects. What my work experience has taught me is that it is possible to manage all those projects without having detailed technical know-how but being a good communicator and enabler for a great team of specialists you can rely on instead. And undoubtedly with a lot of passion for IT projects, communication and management.

Education:
Sports Equipment Technology at the University of applied Science Technikum Wien
Communication and Management at the Danube University Krems
Further trainings in project management, ITIL, Scrum and Quality Management

LINKS:
My blog: http://www.communicationplayground.net/
Linkedin: at.linkedin.com/in/stefanieduchet
Twitter: https://twitter.com/StefanieDuchet

![stefanie_duchet](https://cloud.githubusercontent.com/assets/16474970/13285560/9a6d5e54-dafb-11e5-9aac-b53e055b99b8.jpg)

**Comment by helmuthb** [comment]
The beginning of the talk abstract does not start with a correct sentence.
Also I think the text is way too much (both abstract and bio, like 20%-30% would do it as well.)

I took only parts of it: http://test.womentechmakers.at/schedule/#session-105
Would that be fine already?

**Comment by helmuthb** [comment]
Online after consultation with Stefanie
