### ISSUE TITLE
Decide if website needs updating or not (new images, new fonts, etc)

### ISSUE THREAD

**Issue by helmuthb** [GDGVienna/wtmvienna-site#3]
from trello

**Comment by helmuthb** [comment]
We discussed this, no major changes are foreseen.
The twitter view will be changed to improve readability.

**Comment by helmuthb** [comment]
Twitter feed background updated in b2956606e24ca8feed3eb210ca1d9f7e6e5bb9e5
Is it better now?

**Comment by Kriszlina** [comment]
I like it how it looks now. I think you can close this one.
