### ISSUE TITLE
Create recordings page

### ISSUE THREAD

**Issue by helmuthb** [GDGVienna/wtmvienna-site#6]
We discussed in the IT meeting that we will add a recordings page, similar as on the devfest website, showing the recordings from previous events.

**Comment by helmuthb** [comment]
Implemented in d60300be2d7797adb1333a86262a8163f218c90d (and other commits)

**Comment by theRealImy** [comment]
love this!

Thanks,
Imy

On 4 December 2015 at 14:54, Helmuth Breitenfellner <
notifications@github.com> wrote:

> Closed #6 <https://github.com/GDGVienna/wtmvienna-site/issues/6>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GDGVienna/wtmvienna-site/issues/6#event-482651982>.
>



-- 

*timeaturdean.com <http://timeaturdean.com>*
Technical Consultant @Semantic Web Company <https://www.semantic-web.at/>
Diversity Lead @GDGVienna <http://www.gdg-vienna.at/> & @
WomenTechmakersVienna <http://womentechmakers.at/>
